runtime: java11
service: atrucios
env: standard
# remember to use an instance class compatible with your scaling type
instance_class: B1
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 3
  idle_timeout: 10m
#service_account: sample@appspot.gserviceaccount.com
